const fs = require('fs');
let code = fs.readFileSync('server.ts', 'utf8');
code = code.replace(/interface Business \{[\s\S]*?createdAt: number;\n\}/, `interface Business {
  id: string;
  slug?: string;
  name: string;
  slogan?: string;
  logoUrl?: string;
  certificateOfIncorporationUrl?: string;
  companyProfileUrl?: string;
  rcNumber: string;
  category: string;
  aboutUs?: string;
  services: string;
  phone: string;
  location: string;
  email: string;
  website?: string;
  whatsapp?: string;
  facebookUrl?: string;
  instagramUrl?: string;
  twitterUrl?: string;
  linkedinUrl?: string;
  promoVideoUrl?: string;
  promoPhoto1Url?: string;
  promoPhoto2Url?: string;
  promoPhoto3Url?: string;
  promoPhoto4Url?: string;
  promoPhoto5Url?: string;
  username?: string;
  password?: string;
  verified?: boolean;
  verifiedAt?: number | null;
  createdAt: number;
}`);
fs.writeFileSync('server.ts', code);
